android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
org.gradle.jvmargs=-Xmx8192m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=512m
org.gradle.caching=true
org.gradle.parallel=false
android.suppressUnsupportedCompileSdk=35
