android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=256m
org.gradle.caching=true
org.gradle.parallel=false
android.suppressUnsupportedCompileSdk=35
org.gradle.workers.max=2
